"""add width height

Revision ID: 42c7b73737c3
Revises: 6bfa9e2dced2
Create Date: 2025-12-03 14:03:26.925956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c7b73737c3'
down_revision: Union[str, Sequence[str], None] = '6bfa9e2dced2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('height', sa.Integer(), nullable=True))
    op.alter_column('files', 'filename', new_column_name='file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'height')
    op.drop_column('files', 'width')
    op.alter_column('files', 'file_name', new_column_name='filename')
    # ### end Alembic commands ###
